name: SampleConsoleApplication
sln_path:
  - Project/windows/SampleConsoleApplication.sln
dependencies:
  - masahikotsujita/SampleStaticLibrary
  - masahikotsujita/SampleStaticLibraryA
  - masahikotsujita/SampleStaticLibraryB
  - masahikotsujita/SampleStaticLibraryC
  - masahikotsujita/SampleStaticLibraryD
