name: SampleConsoleApplication
dependencies:
  - masahikotsujita/SampleStaticLibrary
  - masahikotsujita/SampleStaticLibraryA
  - masahikotsujita/SampleStaticLibraryB
  - masahikotsujita/SampleStaticLibraryC
  - masahikotsujita/SampleStaticLibraryD
