name: SampleConsoleApplication
sln_path: Project/windows/SampleConsoleApplication.sln
dependencies:
  - project: masahikotsujita/SampleStaticLibraryD
    version: ^1.0.0
  - project: masahikotsujita/SampleStaticLibraryE
    version: ^1.0.0