name: SampleConsoleApplication
sln_path: Project/windows/SampleConsoleApplication.sln
dependencies:
  - masahikotsujita/SampleStaticLibraryA
  - masahikotsujita/SampleStaticLibraryB
  - masahikotsujita/SampleStaticLibraryC
  - masahikotsujita/SampleStaticLibraryD
  - masahikotsujita/SampleStaticLibraryE